kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: knative-serving-pipelines
  labels:
    serving.knative.dev/release: devel
    serving.knative.dev/controller: "true"
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["pipelines", "tasks", "pipelineresources", "pipelineruns", "taskruns"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]