# Copyright 2019 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-task-run
spec:
  runLatest:
    configuration:
      build:
        apiVersion: tekton.dev/v1alpha1
        kind: TaskRun
        spec:
          serviceAccountName: knative-build
          taskRef:
            name: build-docker-image-from-git-source
          inputs:
            resources:
              - name: docker-source
                resourceRef:
                  name: skaffold-git
            params:
              - name: pathToDockerFile
                value: /workspace/examples/helloworld/Dockerfile
              - name: pathToContext
                value: /workspace/examples/helloworld
          outputs:
            resources:
              - name: builtImage
                resourceRef:
                  name: skaffold-image-leeroy-web
          timeout: 10m
      revisionTemplate:
        spec:
          container:
            image: docker.io/houshengbo/helloworld:latest
            env:
              - name: TARGET
                value: "Knative"
